# Site settings
title: N3RD
baseurl: "/blog.n3rd.nl/" # the subpath of your site, e.g. /blog/
url: "http://n3rd.github.io" # the base hostname & protocol for your site
author:  
  name: Boaz  
  email: 
  github: n3rd
  twitter: boazdenbesten
  pinterest: 
  linkedin: boazdenbesten  
  bio: Nomen est omen
  email_md5: 
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: N3RD - Nomen est omen
  
# Build settings
markdown: kramdown
highlighter: pygments